In [8]:
import json
import numpy as np
import hdbscan
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score
from prefixspan import PrefixSpan
import pickle
import warnings
warnings.filterwarnings('ignore')
from sklearn.ensemble import IsolationForest

In [14]:
X = pickle.load(open('data/X.pckl','rb'))
X_test = pickle.load(open('data/X_test.pckl','rb'))
y_test = pickle.load(open('data/y_test.pckl','rb'))
Xpo = pickle.load(open('data/Xpo.pckl','rb'))
Xpo_test = pickle.load(open('data/Xpo_test.pckl','rb'))
Xpbow = pickle.load(open('data/Xpbow.pckl','rb'))
Xpbow_test = pickle.load(open('data/Xpbow_test.pckl','rb'))

In [27]:
isolFor = IsolationForest()

TypeError: __init__() got an unexpected keyword argument 'behaviour'

# Out of Sample Testing

In [38]:
#Bag of Words
paramsAUCbow = {}
for max_features in [1.,0.5,0.1]:
    for n_estimators in [10,100,200]:
        for max_samples in [100, 256, 500]:
            isolFor = IsolationForest(max_features=max_features, n_estimators=n_estimators, max_samples=max_samples)
            isolFor.fit(X)
            y_pred = isolFor.decision_function(X_test)
            auc = roc_auc_score(y_test, y_pred)
            print(max_features, n_estimators, max_samples, auc)
            paramsAUCbow[auc] = [max_features, n_estimators, max_samples]
maxAucbow = max(paramsAUCbow.keys())
bestParamsAucbow = paramsAUCbow[maxAucbow]
print("Best params: ", bestParamsAucbow, " with AUC: ",maxAucbow)

1.0 10 100 0.355176423973283
1.0 10 256 0.569108823514277
1.0 10 500 0.5129121147720664
1.0 100 100 0.550413465546253
1.0 100 256 0.575324314449939
1.0 100 500 0.5502996145790988
1.0 200 100 0.5058970941631118
1.0 200 256 0.5178778179722435
1.0 200 500 0.5587966274384689
0.5 10 100 0.640677985725533
0.5 10 256 0.6170304322991977
0.5 10 500 0.6253711412884071
0.5 100 100 0.6106637832997999
0.5 100 256 0.5479576294298961
0.5 100 500 0.5040954186885398
0.5 200 100 0.5603313642047414
0.5 200 256 0.5584685822788719
0.5 200 500 0.5196306082857775
0.1 10 100 0.482584018154405
0.1 10 256 0.5643360880550395
0.1 10 500 0.6208145296990218
0.1 100 100 0.5687312499678387
0.1 100 256 0.4983134619441886
0.1 100 500 0.506152454806955
0.1 200 100 0.5012748735418071
0.1 200 256 0.5485629049106431
0.1 200 500 0.5316653630623723
Best params:  [0.5, 10, 100]  with AUC:  0.640677985725533


In [44]:
#Patterns Only
paramsAUCpo = {}
for max_features in [0.1,0.05,0.01]:
    for n_estimators in [10,100,200]:
        for max_samples in [100, 256, 500]:
            isolFor = IsolationForest(max_features=max_features, n_estimators=n_estimators, max_samples=max_samples)
            isolFor.fit(Xpo)
            y_pred = isolFor.decision_function(Xpo_test)
            auc = roc_auc_score(y_test, y_pred)
            print(max_features, n_estimators, max_samples, auc)
            paramsAUCpo[auc] = [max_features, n_estimators, max_samples]
maxAucpo = max(paramsAUCpo.keys())
bestParamsAucpo = paramsAUCpo[maxAucpo]
print("Best params: ", bestParamsAucpo, " with AUC: ",maxAucpo)

0.1 10 100 0.606040919452692
0.1 10 256 0.397777268914698
0.1 10 500 0.38076330319606033
0.1 100 100 0.3284265924984434
0.1 100 256 0.3065852171273021
0.1 100 500 0.3014439132828701
0.1 200 100 0.2898201797944765
0.1 200 256 0.30235793714912035
0.1 200 500 0.29602859524630404
0.05 10 100 0.2999445539357701
0.05 10 256 0.23534667297885586
0.05 10 500 0.25629203480623464
0.05 100 100 0.30301145456510215
0.05 100 256 0.2974282545939187
0.05 100 500 0.31679449707460905
0.05 200 100 0.28570868046085846
0.05 200 256 0.30846279324664366
0.05 200 500 0.3006713990933089
0.01 10 100 0.33784727761111083
0.01 10 256 0.2390805987660356
0.01 10 500 0.6952003777021917
0.01 100 100 0.23921889231370896
0.01 100 256 0.29779425007590066
0.01 100 500 0.3000526158706962
0.01 200 100 0.3061008680975439
0.01 200 256 0.2653878908883206
0.01 200 500 0.32206187317645485
Best params:  [0.01, 10, 500]  with AUC:  0.6952003777021917


In [49]:
#Patterns and Bag of Words
paramsAUCpobow = {}
for max_features in [0.5,0.3,0.2,0.1,0.05,0.01,0.005,0.001]:
    for n_estimators in [10,100,200,300]:
        for max_samples in [50, 100, 256, 500]:
            isolFor = IsolationForest(max_features=max_features, n_estimators=n_estimators, max_samples=max_samples)
            isolFor.fit(Xpbow)
            y_pred = isolFor.decision_function(Xpbow_test)
            auc = roc_auc_score(y_test, y_pred)
            print(max_features, n_estimators, max_samples, auc)
            paramsAUCpobow[auc] = [max_features, n_estimators, max_samples]
maxAucpobow = max(paramsAUCpobow.keys())
bestParamsAucpobow = paramsAUCpobow[maxAucpobow]
print("Best params: ", bestParamsAucpobow, " with AUC: ",maxAucpobow)

0.5 10 50 0.34011400534134706
0.5 10 100 0.3540031801083707
0.5 10 256 0.3611590671682113
0.5 10 500 0.5938852382251085
0.5 100 50 0.30961995646647766
0.5 100 100 0.325524357674713
0.5 100 256 0.3413695821090602
0.5 100 500 0.33394225376029807
0.5 200 50 0.30787166873356553
0.5 200 100 0.31758695126406733
0.5 200 256 0.316315937077079
0.5 200 500 0.313952725476373
0.5 300 50 0.3203373847982587
0.5 300 100 0.31225846871092405
0.5 300 256 0.3123961190327942
0.5 300 500 0.29906333458547957
0.3 10 50 0.38143611738613614
0.3 10 100 0.3633814123180314
0.3 10 256 0.343970787256925
0.3 10 500 0.3130341990295009
0.3 100 50 0.320275635121158
0.3 100 100 0.3278373976627747
0.3 100 256 0.2988671507155244
0.3 100 500 0.35134794399304287
0.3 200 50 0.3062404480968235
0.3 200 100 0.35134601431563345
0.3 200 256 0.2991019281336675
0.3 200 500 0.2839333772442148
0.3 300 50 0.32212555253096486
0.3 300 100 0.31256078483839594
0.3 300 256 0.30399301714068117
0.3 300 500 0.28457017078931524
0.2 10 50 0.379

# In-Sample Testing

In [20]:
n = len(X)
y_total = np.hstack((np.zeros((n,)),y_test))
X_total = np.vstack((X,X_test))
Xpo_total = np.vstack((Xpo,Xpo_test))
Xpbow_total = np.vstack((Xpbow,Xpbow_test))

In [23]:
#Bag of Words
y_pred = isolFor.fit(X_total).predict(X_total)
print(roc_auc_score(y_total, y_pred))

0.555134877368761


In [24]:
#Patterns Only
y_pred = isolFor.fit(Xpo_total).predict(Xpo_total)
print(roc_auc_score(y_total, y_pred))

0.5059005952092812


In [25]:
#Patterns and Bag of Words
y_pred = isolFor.fit(Xpbow_total).predict(Xpbow_total)
print(roc_auc_score(y_total, y_pred))

0.5059005952092812


# More Error Measures

In [39]:
def calcSensAndSpec(cm):
    tn = cm[0,0]
    fn = cm[1,0]
    fp = cm[0,1]
    tp = cm[1,1]
    print(cm)
    TPR = float(tp)/float(tp + fn)
    TNR = float(tn)/float(tn + fp)
    return TPR, TNR

In [43]:
#Bag of Words
isolFor = IsolationForest(max_features=0.5, n_estimators=10, max_samples=100)
isolFor.fit(X)
y_pred_bin = isolFor.predict(X_test)*-1
y_pred_bin = np.where(y_pred_bin == 1, y_pred_bin, 0.)
cm = confusion_matrix(y_test, y_pred_bin)
print(calcSensAndSpec(cm))

[[885 157]
 [743   3]]
(0.004021447721179625, 0.8493282149712092)


In [46]:
#Patterns only
isolFor = IsolationForest(max_features=0.1, n_estimators=10, max_samples=500)
isolFor.fit(Xpo)
y_pred_bin = isolFor.predict(Xpo_test)*-1
y_pred_bin = np.where(y_pred_bin == 1, y_pred_bin, 0.)
cm = confusion_matrix(y_test, y_pred_bin)
print(calcSensAndSpec(cm))

[[1003   39]
 [ 679   67]]
(0.08981233243967829, 0.9625719769673704)


In [50]:
#Patterns and Bag of Words
isolFor = IsolationForest(max_features=0.005, n_estimators=10, max_samples=256)
isolFor.fit(Xpbow)
y_pred_bin = isolFor.predict(Xpbow_test)*-1
y_pred_bin = np.where(y_pred_bin == 1, y_pred_bin, 0.)
cm = confusion_matrix(y_test, y_pred_bin)
print(calcSensAndSpec(cm))

[[976  66]
 [661  85]]
(0.11394101876675604, 0.9366602687140115)
