In [1]:
import json
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score
import pickle
import warnings
warnings.filterwarnings('ignore')
from sklearn.svm import OneClassSVM 

In [2]:
X = pickle.load(open('data/X.pckl','rb'))
X_test = pickle.load(open('data/X_test.pckl','rb'))
y_test = pickle.load(open('data/y_test.pckl','rb'))
Xpo = pickle.load(open('data/Xpo.pckl','rb'))
Xpo_test = pickle.load(open('data/Xpo_test.pckl','rb'))
Xpbow = pickle.load(open('data/Xpbow.pckl','rb'))
Xpbow_test = pickle.load(open('data/Xpbow_test.pckl','rb'))

7.450538542575505e-06

In [42]:
#Bag of Words
paramsAUCbow = {}
scaleFact = 1./(X.shape[1]*X.var())
for gamma in [0.001*scaleFact,0.005*scaleFact,0.01*scaleFact,0.05*scaleFact,0.1*scaleFact,0.5*scaleFact,scaleFact,1.5*scaleFact,2*scaleFact]:
    for nu in [2**i for i in range(-12,-5)]:
        ocsvm = OneClassSVM(gamma=gamma, nu=nu)
        ocsvm.fit(X)
        y_pred = ocsvm.decision_function(X_test)
        auc = roc_auc_score(y_test, y_pred)
        print(gamma, nu, False, auc)
        paramsAUCbow[auc] = [gamma,  nu, False]
        #y_pred_inv = np.ones(y_pred.shape) - y_pred
        #auc_inv = roc_auc_score(y_test, y_pred_inv)
        #print(gamma, nu, True, auc_inv)
        #paramsAUCbow[auc_inv] = [gamma,  nu, True]
maxAucbow = max(paramsAUCbow.keys())
bestParamsAucbow = paramsAUCbow[maxAucbow]
print("Best params: ", bestParamsAucbow, " with AUC: ",maxAucbow)

7.450538542575505e-09 0.0009765625 False 0.5064181070636484
7.450538542575505e-09 0.001953125 False 0.5371218475503389
7.450538542575505e-09 0.00390625 False 0.4638069705093834
7.450538542575505e-09 0.0078125 False 0.4238497836188398
7.450538542575505e-09 0.015625 False 0.3965023953728909
7.450538542575505e-09 0.03125 False 0.3771400122470193
7.450538542575505e-09 0.0625 False 0.4073806301554548
3.7252692712877524e-08 0.0009765625 False 0.5259232863178153
3.7252692712877524e-08 0.001953125 False 0.5504790745781726
3.7252692712877524e-08 0.00390625 False 0.4586431537618417
3.7252692712877524e-08 0.0078125 False 0.4223883745941245
3.7252692712877524e-08 0.015625 False 0.39377897732243106
3.7252692712877524e-08 0.03125 False 0.37474978516258173
3.7252692712877524e-08 0.0625 False 0.40720438628539674
7.450538542575505e-08 0.0009765625 False 0.5451338681541478
7.450538542575505e-08 0.001953125 False 0.5473812991102901
7.450538542575505e-08 0.00390625 False 0.4560805421621649
7.4505385425755

In [43]:
#Patterns Only
paramsAUCpo = {}
scaleFact = 1./(X.shape[1]*X.var())
for gamma in [0.001*scaleFact,0.005*scaleFact,0.01*scaleFact,0.05*scaleFact,0.1*scaleFact,0.5*scaleFact,scaleFact,1.5*scaleFact,2*scaleFact]:
    for nu in [2**i for i in range(-12,-5)]:
        ocsvm = OneClassSVM(gamma=gamma, nu=nu)
        ocsvm.fit(Xpo)
        y_pred = ocsvm.decision_function(Xpo_test)
        auc = roc_auc_score(y_test, y_pred)
        print(gamma, nu, False, auc)
        paramsAUCpo[auc] = [gamma,  nu, False]
        #y_pred_inv = np.ones(y_pred.shape) - y_pred
        #auc_inv = roc_auc_score(y_test, y_pred_inv)
        #print(gamma, nu, True, auc_inv)
        #paramsAUCpo[auc_inv] = [gamma,  nu, True]
maxAucpo = max(paramsAUCpo.keys())
bestParamsAucpo = paramsAUCpo[maxAucpo]
print("Best params: ", bestParamsAucpo, " with AUC: ",maxAucpo)

7.450538542575505e-09 0.000244140625 False 0.7224596440131115
7.450538542575505e-09 0.00048828125 False 0.7276517626959909
7.450538542575505e-09 0.0009765625 False 0.5905211672747295
7.450538542575505e-09 0.001953125 False 0.20266565637333855
7.450538542575505e-09 0.00390625 False 0.2668763153967674
7.450538542575505e-09 0.0078125 False 0.4919718987511128
7.450538542575505e-09 0.015625 False 0.3942948444165427
3.7252692712877524e-08 0.000244140625 False 0.7224596440131115
3.7252692712877524e-08 0.00048828125 False 0.7275880833414807
3.7252692712877524e-08 0.0009765625 False 0.5904542717912038
3.7252692712877524e-08 0.001953125 False 0.20260069056722224
3.7252692712877524e-08 0.00390625 False 0.2668763153967674
3.7252692712877524e-08 0.0078125 False 0.49194359681577504
3.7252692712877524e-08 0.015625 False 0.38693955735773133
7.450538542575505e-08 0.000244140625 False 0.7224596440131115
7.450538542575505e-08 0.00048828125 False 0.7275880833414807
7.450538542575505e-08 0.0009765625 False

In [44]:
#Patterns and Bag of Words
paramsAUCpobow = {}
scaleFact = 1./(X.shape[1]*X.var())
for gamma in [0.001*scaleFact,0.005*scaleFact,0.01*scaleFact,0.05*scaleFact,0.1*scaleFact,0.5*scaleFact,scaleFact,1.5*scaleFact,2*scaleFact]:
    for nu in [2**i for i in range(-12,-5)]:
        ocsvm = OneClassSVM(gamma=gamma, nu=nu)
        ocsvm.fit(Xpbow)
        y_pred = ocsvm.score_samples(Xpbow_test)
        auc = roc_auc_score(y_test, y_pred)
        print(gamma, nu, False, auc)
        paramsAUCpobow[auc] = [gamma,  nu, False]
        #y_pred_inv = np.ones(y_pred.shape) - y_pred
        #auc_inv = roc_auc_score(y_test, y_pred_inv)
        #print(gamma, nu, True, auc_inv)
        #paramsAUCpobow[auc_inv] = [gamma,  nu, True]
maxAucpobow = max(paramsAUCpobow.keys())
bestParamsAucpobow = paramsAUCpobow[maxAucpobow]
print("Best params: ", bestParamsAucpobow, " with AUC: ",maxAucpobow)

7.450538542575505e-09 0.000244140625 False 0.7224596440131115
7.450538542575505e-09 0.00048828125 False 0.7276517626959909
7.450538542575505e-09 0.0009765625 False 0.5905211672747295
7.450538542575505e-09 0.001953125 False 0.20266565637333855
7.450538542575505e-09 0.00390625 False 0.2668763153967674
7.450538542575505e-09 0.0078125 False 0.4919718987511128
7.450538542575505e-09 0.015625 False 0.3942948444165427
3.7252692712877524e-08 0.000244140625 False 0.7224596440131115
3.7252692712877524e-08 0.00048828125 False 0.7275880833414807
3.7252692712877524e-08 0.0009765625 False 0.5904542717912038
3.7252692712877524e-08 0.001953125 False 0.20260069056722224
3.7252692712877524e-08 0.00390625 False 0.2668763153967674
3.7252692712877524e-08 0.0078125 False 0.49194359681577504
3.7252692712877524e-08 0.015625 False 0.38693955735773133
7.450538542575505e-08 0.000244140625 False 0.7224596440131115
7.450538542575505e-08 0.00048828125 False 0.7275880833414807
7.450538542575505e-08 0.0009765625 False

# Further Error Measures

In [21]:
def calcSensAndSpec(cm):
    tn = cm[0,0]
    fn = cm[1,0]
    fp = cm[0,1]
    tp = cm[1,1]
    print(cm)
    TPR = float(tp)/float(tp + fn)
    TNR = float(tn)/float(tn + fp)
    return TPR, TNR

In [47]:
# Bag of Words
ocsvm = OneClassSVM(gamma=3.7252692712877524e-08, nu=0.001953125)
ocsvm.fit(X)
y_pred_bin = ocsvm.predict(X_test)*-1
y_pred_bin = np.where(y_pred_bin == 1, y_pred_bin, 0.)
cm = confusion_matrix(y_test, y_pred_bin)
print(calcSensAndSpec(cm))

[[1040    2]
 [ 746    0]]
(0.0, 0.9980806142034548)


In [48]:
# Patterns only

ocsvm = OneClassSVM(gamma=1.1175807813863257e-05, nu=0.000244140625)
ocsvm.fit(Xpo)
y_pred_bin = ocsvm.predict(Xpo_test)*-1
y_pred_bin = np.where(y_pred_bin == 1, y_pred_bin, 0.)
print(np.unique(y_pred_bin))
cm = confusion_matrix(y_test, y_pred_bin)
print(calcSensAndSpec(cm))

[0. 1.]
[[1034    8]
 [ 739    7]]
(0.00938337801608579, 0.9923224568138196)


In [49]:
# Patterns and Bag of Words 
ocsvm = OneClassSVM(gamma=1.1175807813863257e-05, nu=0.000244140625)
ocsvm.fit(Xpbow)
y_pred_bin = ocsvm.predict(Xpbow_test)*-1
y_pred_bin = np.where(y_pred_bin == 1, y_pred_bin, 0.)
cm = confusion_matrix(y_test, y_pred_bin)
print(calcSensAndSpec(cm))

[[1034    8]
 [ 739    7]]
(0.00938337801608579, 0.9923224568138196)
